apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubewatch-api
spec:
  selector:
    matchLabels:
      app: kubewatch-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s