apiVersion: v2
name: kubewatch-api
version: 0.1.0
description: A Helm chart for Kubernetes API Monitoring

dependencies:
  - name: prometheus
    version: "*"
    repository: "https://prometheus-community.github.io/helm-charts"