name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build Go Application
        run: |
          export GO111MODULE=on
          go mod init || true
          go mod tidy
          go build -o kubewatch-api cmd/main.go

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kubewatch-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/kubewatch-api:latest

  helm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package Helm Chart
        run: |
          helm package deployment/helm
          mkdir -p helm-package
          mv kubewatch-api-*.tgz helm-package/

      - name: Upload Helm Chart as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: helm-package/

  publish:
    needs: helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Configure Git User
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Download Helm Chart Artifact
        uses: actions/download-artifact@v4
        with:
          name: helm-chart
          path: helm-charts/

      - name: Update Helm Repository Index
        run: |
          cd helm-charts/
          helm repo index --url https://Binyamse.github.io/helm-charts/ --merge index.yaml .

      - name: Push Updated Helm Repository to GitHub Pages
        run: |
          cd helm-charts/
          git init
          git add .
          git commit -m "Update Helm chart"
          git branch -M main
          git remote add origin https://github.com/Binyamse/helm-charts.git
          git push -u origin main --force

      - name: Output Helm Repository URL
        run: echo "Helm Repository published at https://Binyamse.github.io/helm-charts/"